class_name UITheme
extends RefCounted
## Builds the game's Theme. Run through `tools/bake_theme.gd`, which writes the
## result to `resources/ui/gub_theme.tres`; the scenes reference that file.
##
## Why generated rather than hand-authored? A Theme for this many controls is
## roughly forty `StyleBoxFlat` sub-resources, and as a `.tres` that is forty
## anonymous blocks of numbers that no diff can explain and no one can comment.
## The same argument the animation graph is built in code for (see
## `GubAnimator`) applies twice over here: written this way, "focus is a
## one-pixel amber ring, everywhere, on everything" is one function instead of
## nine identical blocks that will eventually disagree with each other.
##
## The baked `.tres` is committed, so the editor previews the real thing and a
## fresh clone needs no build step. Do not edit that file by hand — re-bake:
##
##     Godot --headless --path . --script tools/bake_theme.gd

## Windows-first, as the export preset is (PLAN 7.1). Bahnschrift is the DIN-ish
## grotesque that ships with Windows 10/11 and gives headings and numbers a
## harder edge than the engine default; Segoe UI carries body copy. Both fall
## through `allow_system_fallback` to the engine's bundled font if neither is
## installed, so nothing breaks on a machine without them.
const DISPLAY_FACES: PackedStringArray = [
	"Bahnschrift", "Segoe UI Variable Display", "Segoe UI Semibold", "Segoe UI",
]
const BODY_FACES: PackedStringArray = [
	"Segoe UI Variable Text", "Segoe UI", "Noto Sans",
]


## The one entry point. Everything below is private detail.
static func build() -> Theme:
	var theme := Theme.new()
	theme.resource_name = "GUB UI (generated by tools/bake_theme.gd - do not hand-edit)"

	var body := _system_font(BODY_FACES)
	var display := _system_font(DISPLAY_FACES)
	# Tracked-out display face. Wide letter spacing is what makes a short
	# all-caps label read as a heading rather than as shouting.
	var tracked := FontVariation.new()
	tracked.base_font = display
	tracked.spacing_glyph = 3

	theme.default_font = body
	theme.default_font_size = UIPalette.FONT_BODY

	_labels(theme, display, tracked)
	_panels(theme)
	_buttons(theme, display)
	_inputs(theme, body)
	_toggles(theme, body)
	_sliders(theme)
	_scrollbars(theme)
	_misc(theme, body)
	return theme


# ------------------------------------------------------------------ pieces ---

static func _system_font(faces: PackedStringArray) -> SystemFont:
	var font := SystemFont.new()
	font.font_names = faces
	font.allow_system_fallback = true
	# The UI is drawn at whole-pixel sizes and scaled by the viewport, so
	# subpixel positioning buys nothing and costs glyph-cache entries.
	font.subpixel_positioning = TextServer.SUBPIXEL_POSITIONING_DISABLED
	return font


static func _flat(bg: Color, radius: int = UIPalette.RADIUS) -> StyleBoxFlat:
	var box := StyleBoxFlat.new()
	box.bg_color = bg
	box.set_corner_radius_all(radius)
	return box


static func _bordered(bg: Color, border: Color, width: int = 1,
		radius: int = UIPalette.RADIUS) -> StyleBoxFlat:
	var box := _flat(bg, radius)
	box.border_color = border
	box.set_border_width_all(width)
	return box


static func _pad(box: StyleBoxFlat, horizontal: int, vertical: int) -> StyleBoxFlat:
	box.content_margin_left = horizontal
	box.content_margin_right = horizontal
	box.content_margin_top = vertical
	box.content_margin_bottom = vertical
	return box


# ------------------------------------------------------------------ labels ---

static func _labels(theme: Theme, display: Font, tracked: Font) -> void:
	theme.set_color("font_color", "Label", UIPalette.TEXT)
	theme.set_font_size("font_size", "Label", UIPalette.FONT_BODY)

	# Display is the wordmark: enormous, tracked, and used once per screen.
	# Everything else steps down from it.
	_label_variation(theme, "Display", tracked, UIPalette.FONT_DISPLAY, UIPalette.GUB)
	_label_variation(theme, "Head", display, UIPalette.FONT_HEAD, UIPalette.TEXT)
	_label_variation(theme, "Lead", display, UIPalette.FONT_LEAD, UIPalette.TEXT)
	# Section headings: small, tracked, dim. They label a panel without
	# competing with anything inside it.
	_label_variation(theme, "Section", tracked, UIPalette.FONT_TINY, UIPalette.TEXT_FAINT)
	_label_variation(theme, "Dim", null, UIPalette.FONT_BODY, UIPalette.TEXT_DIM)
	_label_variation(theme, "Small", null, UIPalette.FONT_SMALL, UIPalette.TEXT_DIM)
	_label_variation(theme, "Tiny", null, UIPalette.FONT_TINY, UIPalette.TEXT_FAINT)
	_label_variation(theme, "Accent", display, UIPalette.FONT_BODY, UIPalette.AMBER)
	# Numbers the player reads under pressure: the clock, a score, a countdown.
	_label_variation(theme, "Readout", display, UIPalette.FONT_HEAD, UIPalette.TEXT)


static func _label_variation(theme: Theme, name: String, font: Font, size: int,
		colour: Color) -> void:
	var type := name + "Label"
	theme.set_type_variation(type, "Label")
	if font != null:
		theme.set_font("font", type, font)
	theme.set_font_size("font_size", type, size)
	theme.set_color("font_color", type, colour)


# ------------------------------------------------------------------ panels ---

static func _panels(theme: Theme) -> void:
	# The default panel is glass: translucent, hairline-edged. Both the menu and
	# the lobby have live 3D behind them, and an opaque panel throws that away.
	theme.set_stylebox("panel", "Panel", _bordered(UIPalette.PANEL, UIPalette.LINE))
	theme.set_stylebox("panel", "PanelContainer", _bordered(UIPalette.PANEL, UIPalette.LINE))

	theme.set_type_variation("CardPanel", "PanelContainer")
	theme.set_stylebox("panel", "CardPanel",
		_pad(_bordered(UIPalette.PANEL, UIPalette.LINE), UIPalette.PAD, UIPalette.PAD))

	theme.set_type_variation("RowPanel", "PanelContainer")
	# Deliberately tight: a full eight-player roster has to fit the lobby's list
	# without a scroll bar, and a scroll bar in a list of eight is a design that
	# has given up.
	theme.set_stylebox("panel", "RowPanel", _pad(_flat(UIPalette.RAISED), 14, 5))

	# The HUD has no 3D "behind" to preserve, because it *is* on top of the
	# game. Its panels are barely there at all and never bordered: a hairline
	# box around a kill feed is one more edge competing with the crosshair.
	theme.set_type_variation("HudPanel", "PanelContainer")
	theme.set_stylebox("panel", "HudPanel",
		_pad(_flat(Color(0.02, 0.027, 0.04, 0.55)), 14, 8))

	theme.set_type_variation("ScrimPanel", "PanelContainer")
	theme.set_stylebox("panel", "ScrimPanel", _flat(Color(0.008, 0.012, 0.02, 0.86), 0))


# ----------------------------------------------------------------- buttons ---

static func _buttons(theme: Theme, display: Font) -> void:
	theme.set_font("font", "Button", display)
	theme.set_font_size("font_size", "Button", UIPalette.FONT_BODY)
	theme.set_color("font_color", "Button", UIPalette.TEXT)
	theme.set_color("font_hover_color", "Button", UIPalette.AMBER_GLOW)
	theme.set_color("font_pressed_color", "Button", UIPalette.AMBER)
	theme.set_color("font_focus_color", "Button", UIPalette.TEXT)
	theme.set_color("font_disabled_color", "Button", UIPalette.TEXT_FAINT)
	theme.set_stylebox("normal", "Button",
		_pad(_bordered(UIPalette.RAISED, UIPalette.LINE), 22, 11))
	theme.set_stylebox("hover", "Button",
		_pad(_bordered(Color(0.13, 0.14, 0.15, 0.95), UIPalette.AMBER_DIM), 22, 11))
	theme.set_stylebox("pressed", "Button",
		_pad(_bordered(Color(0.18, 0.13, 0.06, 0.98), UIPalette.AMBER), 22, 11))
	theme.set_stylebox("disabled", "Button",
		_pad(_bordered(Color(0.05, 0.06, 0.08, 0.7), Color(0.4, 0.45, 0.5, 0.09)), 22, 11))
	# One focus ring for the whole UI, so keyboard users get the same amber
	# outline on a button, a text field and a dropdown. It is drawn outside the
	# control rather than inside it, so gaining focus never shifts the layout.
	theme.set_stylebox("focus", "Button", _focus_ring())

	# Primary: at most one per screen. Filled amber with dark text, the only
	# solid accent fill anywhere in the UI, so it cannot be missed.
	theme.set_type_variation("PrimaryButton", "Button")
	theme.set_color("font_color", "PrimaryButton", UIPalette.TEXT_ON_ACCENT)
	theme.set_color("font_hover_color", "PrimaryButton", UIPalette.TEXT_ON_ACCENT)
	theme.set_color("font_pressed_color", "PrimaryButton", UIPalette.TEXT_ON_ACCENT)
	theme.set_color("font_disabled_color", "PrimaryButton", Color(0.45, 0.48, 0.52))
	theme.set_stylebox("normal", "PrimaryButton", _pad(_flat(UIPalette.AMBER), 26, 12))
	theme.set_stylebox("hover", "PrimaryButton", _pad(_flat(UIPalette.AMBER_GLOW), 26, 12))
	theme.set_stylebox("pressed", "PrimaryButton", _pad(_flat(UIPalette.AMBER_DIM), 26, 12))
	theme.set_stylebox("disabled", "PrimaryButton",
		_pad(_bordered(Color(0.07, 0.08, 0.1, 0.8), Color(0.4, 0.45, 0.5, 0.1)), 26, 12))

	# Nav: the main menu's own list. No box at all until you touch it, and a
	# thick amber bar down the left edge when you do, so the row you are on
	# reads from the corner of the eye.
	theme.set_type_variation("NavButton", "Button")
	theme.set_font_size("font_size", "NavButton", UIPalette.FONT_LEAD)
	theme.set_color("font_color", "NavButton", UIPalette.TEXT_DIM)
	theme.set_color("font_hover_color", "NavButton", UIPalette.GUB)
	theme.set_color("font_pressed_color", "NavButton", UIPalette.AMBER)
	theme.set_color("font_focus_color", "NavButton", UIPalette.GUB)
	theme.set_stylebox("normal", "NavButton", _nav_box(Color(0, 0, 0, 0), Color(0, 0, 0, 0)))
	theme.set_stylebox("hover", "NavButton",
		_nav_box(Color(0.10, 0.11, 0.13, 0.75), UIPalette.AMBER))
	theme.set_stylebox("pressed", "NavButton",
		_nav_box(Color(0.16, 0.12, 0.06, 0.9), UIPalette.GUB))
	theme.set_stylebox("focus", "NavButton",
		_nav_box(Color(0.10, 0.11, 0.13, 0.6), UIPalette.AMBER_DIM))
	theme.set_stylebox("disabled", "NavButton", _nav_box(Color(0, 0, 0, 0), Color(0, 0, 0, 0)))

	# Ghost: borderless, for anything secondary - a copy button, a back arrow.
	theme.set_type_variation("GhostButton", "Button")
	theme.set_font_size("font_size", "GhostButton", UIPalette.FONT_SMALL)
	theme.set_color("font_color", "GhostButton", UIPalette.TEXT_DIM)
	theme.set_stylebox("normal", "GhostButton", _pad(_flat(Color(0, 0, 0, 0)), 12, 7))
	theme.set_stylebox("hover", "GhostButton", _pad(_flat(Color(0.14, 0.15, 0.17, 0.8)), 12, 7))
	theme.set_stylebox("pressed", "GhostButton", _pad(_flat(Color(0.2, 0.15, 0.07, 0.9)), 12, 7))
	theme.set_stylebox("disabled", "GhostButton", _pad(_flat(Color(0, 0, 0, 0)), 12, 7))

	# Danger: leaving, quitting. Red only on hover, because a permanently red
	# button among grey ones draws the eye to the one action nobody is hunting
	# for.
	theme.set_type_variation("DangerButton", "Button")
	theme.set_color("font_hover_color", "DangerButton", UIPalette.DANGER)
	theme.set_color("font_pressed_color", "DangerButton", UIPalette.DANGER)
	theme.set_stylebox("hover", "DangerButton",
		_pad(_bordered(Color(0.16, 0.06, 0.05, 0.95), UIPalette.DANGER.darkened(0.35)), 22, 11))
	theme.set_stylebox("pressed", "DangerButton",
		_pad(_bordered(Color(0.22, 0.07, 0.06, 0.98), UIPalette.DANGER), 22, 11))


static func _nav_box(bg: Color, bar: Color) -> StyleBoxFlat:
	var box := _flat(bg, 2)
	box.border_color = bar
	box.border_width_left = 4
	return _pad(box, 22, 13)


static func _focus_ring() -> StyleBoxFlat:
	var box := _flat(Color(0, 0, 0, 0))
	box.draw_center = false
	box.border_color = UIPalette.AMBER
	box.set_border_width_all(1)
	box.set_expand_margin_all(2)
	return box


# ------------------------------------------------------------------ inputs ---

static func _inputs(theme: Theme, body: Font) -> void:
	theme.set_font("font", "LineEdit", body)
	theme.set_font_size("font_size", "LineEdit", UIPalette.FONT_BODY)
	theme.set_color("font_color", "LineEdit", UIPalette.TEXT)
	theme.set_color("font_placeholder_color", "LineEdit", UIPalette.TEXT_FAINT)
	theme.set_color("font_uneditable_color", "LineEdit", UIPalette.TEXT_DIM)
	theme.set_color("caret_color", "LineEdit", UIPalette.AMBER)
	theme.set_color("selection_color", "LineEdit", Color(1.0, 0.64, 0.26, 0.28))
	theme.set_stylebox("normal", "LineEdit",
		_pad(_bordered(Color(0.02, 0.027, 0.04, 0.85), UIPalette.LINE), 14, 10))
	theme.set_stylebox("focus", "LineEdit",
		_pad(_bordered(Color(0.03, 0.035, 0.05, 0.95), UIPalette.AMBER), 14, 10))
	theme.set_stylebox("read_only", "LineEdit",
		_pad(_bordered(Color(0.03, 0.035, 0.05, 0.5), Color(0.4, 0.45, 0.5, 0.08)), 14, 10))

	theme.set_font_size("font_size", "OptionButton", UIPalette.FONT_SMALL)
	theme.set_color("font_color", "OptionButton", UIPalette.TEXT)
	theme.set_color("font_hover_color", "OptionButton", UIPalette.AMBER_GLOW)
	theme.set_color("font_disabled_color", "OptionButton", UIPalette.TEXT_FAINT)
	for state: String in ["normal", "hover", "pressed", "disabled"]:
		var tint: Color = UIPalette.AMBER_DIM if state == "hover" else UIPalette.LINE
		theme.set_stylebox(state, "OptionButton",
			_pad(_bordered(Color(0.02, 0.027, 0.04, 0.85), tint), 14, 8))
	theme.set_stylebox("focus", "OptionButton", _focus_ring())

	theme.set_stylebox("panel", "PopupMenu",
		_bordered(Color(0.035, 0.045, 0.062, 0.99), UIPalette.LINE_STRONG))
	theme.set_stylebox("hover", "PopupMenu", _flat(Color(0.17, 0.13, 0.06, 1.0)))
	theme.set_color("font_color", "PopupMenu", UIPalette.TEXT)
	theme.set_color("font_hover_color", "PopupMenu", UIPalette.AMBER_GLOW)
	theme.set_font_size("font_size", "PopupMenu", UIPalette.FONT_SMALL)


static func _toggles(theme: Theme, body: Font) -> void:
	for type: String in ["CheckButton", "CheckBox"]:
		theme.set_font("font", type, body)
		theme.set_font_size("font_size", type, UIPalette.FONT_SMALL)
		theme.set_color("font_color", type, UIPalette.TEXT_DIM)
		theme.set_color("font_hover_color", type, UIPalette.TEXT)
		theme.set_color("font_pressed_color", type, UIPalette.GUB)
		for state: String in ["normal", "hover", "pressed", "disabled"]:
			theme.set_stylebox(state, type, _pad(_flat(Color(0, 0, 0, 0)), 4, 6))
		theme.set_stylebox("focus", type, _focus_ring())


static func _sliders(theme: Theme) -> void:
	var track := _flat(Color(0.02, 0.027, 0.04, 0.9), 3)
	track.content_margin_top = 3
	track.content_margin_bottom = 3
	theme.set_stylebox("slider", "HSlider", track)
	theme.set_stylebox("grabber_area", "HSlider", _flat(UIPalette.AMBER_DIM, 3))
	theme.set_stylebox("grabber_area_highlight", "HSlider", _flat(UIPalette.AMBER, 3))


static func _scrollbars(theme: Theme) -> void:
	for type: String in ["VScrollBar", "HScrollBar"]:
		theme.set_stylebox("scroll", type, _flat(Color(0.02, 0.027, 0.04, 0.5), 3))
		theme.set_stylebox("grabber", type, _flat(Color(0.30, 0.35, 0.42, 0.7), 3))
		theme.set_stylebox("grabber_highlight", type, _flat(UIPalette.AMBER_DIM, 3))
		theme.set_stylebox("grabber_pressed", type, _flat(UIPalette.AMBER, 3))


static func _misc(theme: Theme, body: Font) -> void:
	theme.set_stylebox("panel", "ScrollContainer", StyleBoxEmpty.new())

	theme.set_font("normal_font", "RichTextLabel", body)
	theme.set_font_size("normal_font_size", "RichTextLabel", UIPalette.FONT_SMALL)
	theme.set_color("default_color", "RichTextLabel", UIPalette.TEXT_DIM)
	theme.set_stylebox("normal", "RichTextLabel", StyleBoxEmpty.new())
	theme.set_stylebox("focus", "RichTextLabel", StyleBoxEmpty.new())

	var rule := _flat(UIPalette.LINE, 0)
	rule.content_margin_top = 1
	theme.set_stylebox("separator", "HSeparator", rule)
	theme.set_constant("separation", "HSeparator", 1)

	theme.set_stylebox("background", "ProgressBar", _flat(Color(0.02, 0.027, 0.04, 0.9), 2))
	theme.set_stylebox("fill", "ProgressBar", _flat(UIPalette.AMBER, 2))
	theme.set_color("font_color", "ProgressBar", UIPalette.TEXT_DIM)
	theme.set_font_size("font_size", "ProgressBar", UIPalette.FONT_TINY)
